oedict = [
["ac", "but"],
["and, ond", "and"],
["andswarian", "answer"],
["ābīdan", "await"],
["āc (f.)", "oak"],
["ādreccan", "afflict"],
["ālīesan", "set free, release"],
["ān and twentig", "21"],
["ān", "one"],
["ārian", "honor, to endow"],
["āscian", "ask, enquire"],
["āð (m.)", "oath"],
["æcer (m.)", "field"],
["æcs (m.)", "axe"],
["æfter", "after"],
["æt", "at"],
["æðele", "noble"],
["æðeling (m.)", "prince"],
["ǣr", "before"],
["bān (n.)", "bone"],
["bāt (m.)", "boat"],
["be", "by, beside"],
["bearn (n.)", "child"],
["benn (f.)", "wound"],
["betwēonan / betwux", "between / betwixt"],
["bēotian", "boast, promise"],
["biscop (m.)", "bishop"],
["bismrian", "besmirch, insult"],
["blind", "blind"],
["blissian", "be happy, rejoice"],
["bodian", "preach"],
["bōc (f.)", "book"],
["bōt (f.)", "remedy"],
["brād", "broad"],
["brim (n.)", "sea"],
["brūcan", "enjoy"],
["bryd (f.)", "bride"],
["burg (f.)", "stronghold"],
["būtan", "without, except for"],
["bæcere (m.)", "baker"],
["bærnan", "burn up"],
["cearu (f.)", "care, grief, worry"],
["ceorfan", "cut"],
["clipian", "call out to"],
["cnyssan", "strike"],
["cnyttan", "tie a knot"],
["cuman", "come"],
["cwīðan", "mourn"],
["cyning (m.)", "king"],
["cȳðan", "declare, to make known"],
["Dene", "Danes, vikings"],
["derian", "hurt"],
["dēad", "dead"],
["dēman", "judge"],
["dēore", "dear, precious"],
["drǣfan", "drive out, expel"],
["dynnan", "make a loud noise"],
["eahta", "eight"],
["eald", "old"],
["eard (m.)", "estate"],
["eardian", "dwell"],
["earm", "poor"],
["ebbian", "ebb away"],
["ecg (f.)", "edge"],
["endian", "finish, end"],
["endleofon", "eleven"],
["Englaland", "England"],
["Engle", "Angles, Englishmen"],
["erian", "plough"],
["eroðlic", "worldly"],
["eroðling (m.)", "a farmer, ploughman"],
["ēac", "also"],
["fandian", "try, test"],
["faran", "travel"],
["fāh", "hostile"],
["fealu", "dark"],
["ferian", "carry"],
["fēdan", "feed"],
["fēower", "four"],
["fēowertig", "forty"],
["fēowertīene", "fourteen"],
["fīf", "five"],
["fīftig", "fifty"],
["flāh", "treacherous"],
["flīeman", "drive off, rout"],
["flōwan", "flow"],
["folc (n.)", "a folk, nation"],
["folgian", "follow"],
["for", "for, on behalf of"],
["fore", "before, in front of"],
["forhtian", "be afraid, fear"],
["forðǣm ðe", "because of"],
["fōt (m.)", "foot"],
["fram", "from"],
["fremman", "carry out, perform"],
["frēoh", "free"],
["frēond (m.)", "friend"],
["gaderian", "gather"],
["galdor (n.)", "charm"],
["gān", "go"],
["gearu", "ready, prepared"],
["gefeoht (n.)", "battle, fight"],
["gehālsian", "take an oath"],
["geond", "across, throughout"],
["gesīð (m.)", "a companion, fellow traveller"],
["geǣmetigan", "empty"],
["giefan", "give"],
["giefu (f.)", "gift"],
["gīeman", "heed, obey"],
["glōf (f.)", "glove"],
["glæd", "happy"],
["gōd", "good"],
["gōs (f.)", "goose"],
["gram", "fierce, angry"],
["habban", "have"],
["heard", "hard"],
["helpan", "help"],
["here (m.)", "raiding party, enemy army"],
["hergian", "ravage, to harry"],
["herian", "praise"],
["hēah", "high"],
["hēawan", "hew"],
["hierde (m.)", "herdsman"],
["hīeran", "hear"],
["hīersumian", "obey"],
["hlāf (m.)", "loaf"],
["hors (n.)", "horse"],
["hrēowan", "rue"],
["hund, hundred, hundtigontig", "100"],
["hundeahtatig", "80"],
["hundendleofontig", "110"],
["hundseofontig", "70"],
["hundtwelftig", "120"],
["hūs (n.)", "house"],
["hwȳ", "why?"],
["hwæt", "bold, daring"],
["hyll (f.)", "hill"],
["hǣlan", "heal, make whole"],
["land (n.)", "land"],
["lāf (f.)", "inheritance"],
["lār (f.)", "learning, knowledge"],
["lāðlic", "hateful"],
["leornian", "learn"],
["lettan", "hinder"],
["lēode", "people"],
["lēof", "dear, precious"],
["liðmann (m.)", "sailor"],
["lof (n.)", "praise"],
["longsum", "enduring"],
["losian", "be lost"],
["lōcian", "look"],
["lufian", "love"],
["lufsum", "lovable"],
["lūs (f.)", "louse"],
["lȳtel", "small"],
["lǣce (m.)", "a healer, doctor"],
["lǣfan", "leave behind"],
["lǣran", "teach"],
["macian", "make"],
["mann (m.)", "man"],
["maðelian", "make a speech"],
["mid", "with"],
["mōna (m.)", "moon"],
["munt (m.)", "mount, hill"],
["mūs (f.)", "mouse"],
["mynster (n.)", "minister-church"],
["mǣre", "famous, renowned"],
["nā", "not at all"],
["nān", "none"],
["ne... ne", "neither ... nor"],
["nearu", "narrow, close"],
["nerian", "save"],
["nēah", "near"],
["nigon", "nine"],
["niht (f.)", "night"],
["nīedan", "compel, to force"],
["Norðanhymbre", "Northumbrians"],
["nælles", "by no means"],
["nǣfre", "never"],
["of", "off, from, away from"],
["ofer", "over, beyond, the other side of"],
["oftost", "most often"],
["on", "onto, into, against"],
["oneardian", "live in, to inhabit"],
["ongēan", "towards, against"],
["oð", "as far as, until, up to"],
["oððe", "or"],
["rāp (m.)", "rope"],
["rīce (n.)", "kingdom"],
["rīce", "powerful"],
["rīdan", "ride"],
["rūm", "spacious, roomy"],
["rȳman", "make room"],
["rǣran", "raise, rear"],
["sacu (f.)", "strife"],
["sār", "sore"],
["sārian", "be painful"],
["scēap (n.)", "sheep"],
["scip (n.)", "ship"],
["scīnan", "shine"],
["scwēawian", "look at, inspect"],
["Seaxe", "Saxons"],
["seldan", "seldom"],
["seofon", "seven"],
["settan", "set"],
["sēcan", "seek"],
["sēoc", "sick"],
["siex", "six"],
["siextig", "sixty"],
["smæl", "slender"],
["sorgian", "sorrow, grieve"],
["sōna", "soon"],
["spyrian", "ask, inquire"],
["standan", "stand"],
["stān (m.)", "stone"],
["stede (m.)", "place"],
["stēorbord (n.)", "starboard"],
["sunne (f.)", "sun"],
["sweorcan", "darken"],
["sweord (n.)", "sword"],
["swēte", "sweet"],
["swīðe", "very much, greatly"],
["talu (f.)", "tale"],
["til", "good, gainful"],
["tīen", "ten"],
["tōð (m.)", "tooth"],
["trēow (n.)", "tree"],
["trum", "firm, stout"],
["trūwian", "trust, to believe"],
["trymman", "strengthen"],
["tungol  (n.)", "star"],
["tū hund", "200"],
["tū ðūsund", "2000"],
["twelf", "twelve"],
["twentig", "twenty"],
["twēgen", "two"],
["twēolic", "doubtful"],
["ðegn (m.)", "thane"],
["ðrēotīene", "thirteen"],
["ðrīe", "three"],
["ðrītig", "thirty"],
["ðurh", "through, by means of"],
["ðūsund", "1000"],
["ðweorh", "awkward, perverse"],
["wadan", "walk"],
["weaxan", "grow"],
["weorðian", "honour"],
["wer (m.)", "man"],
["werian", "protect"],
["wēnan", "expect, hope, suppose"],
["wif (f.)", "woman"],
["wilsum", "enjoyable"],
["wið", "against, towards, along"],
["wīcing (m.)", "viking"],
["word (n.)", "word"],
["wull (f.)", "wool"],
["wundian", "wound"],
["wunian", "remain, to dwell"],
["yfel", "evil"],
["ylde", "men, human beings"],
["ylfe", "elves"],
["ymb", "around, about"]
];
