oedict = [
["mann (m.)", "man"],
["talu (f.)", "tale"],
["land (n.)", "land"],
["stān (m.)", "stone"],
["wer (m.)", "man"],
["wif (f.)", "woman"],
["cyning (m.)", "king"],
["mōna (m.)", "moon"],
["bryd (f.)", "bride"],
["sunne (f.)", "sun"],
["niht (f.)", "night"],
["scip (n.)", "ship"],
["hors (n.)", "horse"],
["tungol  (n.)", "star"],
["rīdan", "ride"],
["wadan", "walk"],
["cuman", "come"],
["scīnan", "shine"],
["sweorcan", "darken"],
["ābīdan", "await"],
["habban", "have"],
["ðegn (m.)", "thane"],
["biscop (m.)", "bishop"],
["āð (m.)", "oath"],
["bāt (m.)", "boat"],
["æðeling (m.)", "prince"],
["liðmann (m.)", "sailor"],
["lār (f.)", "learning, knowledge"],
["giefu (f.)", "gift"],
["glōf (f.)", "glove"],
["cearu (f.)", "care, grief, worry"],
["sacu (f.)", "strife"],
["hūs (n.)", "house"],
["word (n.)", "word"],
["rīce (n.)", "kingdom"],
["brim (n.)", "sea"],
["bān (n.)", "bone"],
["folc (n.)", "a folk, nation"],
["sweord (n.)", "sword"],
["lof (n.)", "praise"],
["ādreccan", "afflict"],
["sēcan", "seek"],
["hīeran", "hear"],
["lufian", "love"],
["oneardian", "live in, to inhabit"],
["giefan", "give"],
["and, ond", "and"],
["ne... ne", "neither ... nor"],
["ac", "but"],
["ēac", "also"],
["oððe", "or"],
["nā", "not at all"],
["nǣfre", "never"],
["nælles", "by no means"],
["bæcere (m.)", "baker"],
["hierde (m.)", "herdsman"],
["hlāf (m.)", "loaf"],
["lǣce (m.)", "a healer, doctor"],
["here (m.)", "raiding party, enemy army"],
["bōt (f.)", "remedy"],
["ecg (f.)", "edge"],
["benn (f.)", "wound"],
["trēow (n.)", "tree"],
["bearn (n.)", "child"],
["scēap (n.)", "sheep"],
["ālīesan", "set free, release"],
["cȳðan", "declare, to make known"],
["gīeman", "heed, obey"],
["cwīðan", "mourn"],
["fēdan", "feed"],
["hǣlan", "heal, make whole"],
["nīedan", "compel, to force"],
["rȳman", "make room"],
["bærnan", "burn up"],
["lǣran", "teach"],
["dēman", "judge"],
["drǣfan", "drive out, expel"],
["flīeman", "drive off, rout"],
["lǣfan", "leave behind"],
["rǣran", "raise, rear"],
["wēnan", "expect, hope, suppose"],
["trum", "firm, stout"],
["longsum", "enduring"],
["lufsum", "lovable"],
["twēolic", "doubtful"],
["til", "good, gainful"],
["wilsum", "enjoyable"],
["lāðlic", "hateful"],
["eroðlic", "worldly"],
["lēof", "dear, precious"],
["gōd", "good"],
["blind", "blind"],
["yfel", "evil"],
["earm", "poor"],
["heard", "hard"],
["eald", "old"],
["rīce", "powerful"],
["æðele", "noble"],
["dēore", "dear, precious"],
["mǣre", "famous, renowned"],
["swēte", "sweet"],
["fealu", "dark"],
["gearu", "ready, prepared"],
["nearu", "narrow, close"],
["hēah", "high"],
["ðweorh", "awkward, perverse"],
["flāh", "treacherous"],
["frēoh", "free"],
["fāh", "hostile"],
["nēah", "near"],
["hwæt", "bold, daring"],
["glæd", "happy"],
["lȳtel", "small"],
["gram", "fierce, angry"],
["dēad", "dead"],
["smæl", "slender"],
["munt (m.)", "mount, hill"],
["stede (m.)", "place"],
["æcer (m.)", "field"],
["hyll (f.)", "hill"],
["lāf (f.)", "inheritance"],
["stēorbord (n.)", "starboard"],
["mynster (n.)", "minister-church"],
["ān", "one"],
["twēgen", "two"],
["ðrīe", "three"],
["fēower", "four"],
["fīf", "five"],
["siex", "six"],
["seofon", "seven"],
["eahta", "eight"],
["nigon", "nine"],
["tīen", "ten"],
["endleofon", "eleven"],
["twelf", "twelve"],
["ðrēotīene", "thirteen"],
["fēowertīene", "fourteen"],
["twentig", "twenty"],
["ān and twentig", "21"],
["ðrītig", "thirty"],
["fēowertig", "forty"],
["siextig", "sixty"],
["fīftig", "fifty"],
["hundseofontig", "70"],
["hundeahtatig", "80"],
["hund, hundred, hundtigontig", "100"],
["hundendleofontig", "110"],
["hundtwelftig", "120"],
["tū hund", "200"],
["ðūsund", "1000"],
["tū ðūsund", "2000"],
["fore", "before, in front of"],
["geond", "across, throughout"],
["ofer", "over, beyond, the other side of"],
["on", "onto, into, against"],
["ongēan", "towards, against"],
["oð", "as far as, until, up to"],
["ðurh", "through, by means of"],
["wið", "against, towards, along"],
["ymb", "around, about"],
["æfter", "after"],
["ǣr", "before"],
["æt", "at"],
["be", "by, beside"],
["betwēonan / betwux", "between / betwixt"],
["būtan", "without, except for"],
["for", "for, on behalf of"],
["fram", "from"],
["mid", "with"],
["of", "off, from, away from"],
["nān", "none"],
["sār", "sore"],
["brād", "broad"],
["rūm", "spacious, roomy"],
["sēoc", "sick"],
["wīcing (m.)", "viking"],
["sōna", "soon"],
["Englaland", "England"],
["ylde", "men, human beings"],
["ylfe", "elves"],
["lēode", "people"],
["Engle", "Angles, Englishmen"],
["Seaxe", "Saxons"],
["Norðanhymbre", "Northumbrians"],
["Dene", "Danes, vikings"],
["fremman", "carry out, perform"],
["trymman", "strengthen"],
["dynnan", "make a loud noise"],
["cnyssan", "strike"],
["settan", "set"],
["lettan", "hinder"],
["cnyttan", "tie a knot"],
["nerian", "save"],
["erian", "plough"],
["derian", "hurt"],
["herian", "praise"],
["ferian", "carry"],
["werian", "protect"],
["spyrian", "ask, inquire"],
["eroðling (m.)", "a farmer, ploughman"],
["æcs (m.)", "axe"],
["wull (f.)", "wool"],
["galdor (n.)", "charm"],
["eard (m.)", "estate"],
["oftost", "most often"],
["hwȳ", "why?"],
["seldan", "seldom"],
["swīðe", "very much, greatly"],
["forðǣm ðe", "because of"],
["fōt (m.)", "foot"],
["tōð (m.)", "tooth"],
["frēond (m.)", "friend"],
["bōc (f.)", "book"],
["gōs (f.)", "goose"],
["burg (f.)", "stronghold"],
["āc (f.)", "oak"],
["mūs (f.)", "mouse"],
["lūs (f.)", "louse"],
["standan", "stand"],
["faran", "travel"],
["helpan", "help"],
["gān", "go"],
["flōwan", "flow"],
["brūcan", "enjoy"],
["ceorfan", "cut"],
["weaxan", "grow"],
["hrēowan", "rue"],
["hēawan", "hew"],
["endian", "finish, end"],
["āscian", "ask, enquire"],
["bismrian", "besmirch, insult"],
["bodian", "preach"],
["eardian", "dwell"],
["fandian", "try, test"],
["gaderian", "gather"],
["hergian", "ravage, to harry"],
["leornian", "learn"],
["losian", "be lost"],
["scwēawian", "look at, inspect"],
["weorðian", "honour"],
["wundian", "wound"],
["forhtian", "be afraid, fear"],
["sārian", "be painful"],
["gehālsian", "take an oath"],
["andswarian", "answer"],
["bēotian", "boast, promise"],
["blissian", "be happy, rejoice"],
["clipian", "call out to"],
["ebbian", "ebb away"],
["folgian", "follow"],
["geǣmetigan", "empty"],
["hīersumian", "obey"],
["lōcian", "look"],
["macian", "make"],
["trūwian", "trust, to believe"],
["wunian", "remain, to dwell"],
["ārian", "honor, to endow"],
["maðelian", "make a speech"],
["sorgian", "sorrow, grieve"],
["gesīð (m.)", "a companion, fellow traveller"],
["rāp (m.)", "rope"],
["gefeoht (n.)", "battle, fight"]];