oedict = [
["ac", "but"],
["and, ond", "and"],
["andswarian", "answer"],
["a&#x0304;bi&#x0304;dan", "await"],
["a&#x0304;c (f.)", "oak"],
["a&#x0304;dreccan", "afflict"],
["a&#x0304;li&#x0304;esan", "set free, release"],
["a&#x0304;n and twentig", "21"],
["a&#x0304;n", "one"],
["a&#x0304;rian", "honor, to endow"],
["a&#x0304;scian", "ask, enquire"],
["a&#x0304;&eth; (m.)", "oath"],
["&aelig;cer (m.)", "field"],
["&aelig;cs (m.)", "axe"],
["&aelig;fter", "after"],
["&aelig;t", "at"],
["&aelig;&eth;ele", "noble"],
["&aelig;&eth;eling (m.)", "prince"],
["&aelig;&#x0304;r", "before"],
["ba&#x0304;n (n.)", "bone"],
["ba&#x0304;t (m.)", "boat"],
["be", "by, beside"],
["bearn (n.)", "child"],
["benn (f.)", "wound"],
["betwe&#x0304;onan / betwux", "between / betwixt"],
["be&#x0304;otian", "boast, promise"],
["biscop (m.)", "bishop"],
["bismrian", "besmirch, insult"],
["blind", "blind"],
["blissian", "be happy, rejoice"],
["bodian", "preach"],
["bo&#x0304;c (f.)", "book"],
["bo&#x0304;t (f.)", "remedy"],
["bra&#x0304;d", "broad"],
["brim (n.)", "sea"],
["bru&#x0304;can", "enjoy"],
["bryd (f.)", "bride"],
["burg (f.)", "stronghold"],
["bu&#x0304;tan", "without, except for"],
["b&aelig;cere (m.)", "baker"],
["b&aelig;rnan", "burn up"],
["cearu (f.)", "care, grief, worry"],
["ceorfan", "cut"],
["clipian", "call out to"],
["cnyssan", "strike"],
["cnyttan", "tie a knot"],
["cuman", "come"],
["cwi&#x0304;&eth;an", "mourn"],
["cyning (m.)", "king"],
["cy&#x0304;&eth;an", "declare, to make known"],
["Dene", "Danes, vikings"],
["derian", "hurt"],
["de&#x0304;ad", "dead"],
["de&#x0304;man", "judge"],
["de&#x0304;ore", "dear, precious"],
["dr&aelig;&#x0304;fan", "drive out, expel"],
["dynnan", "make a loud noise"],
["eahta", "eight"],
["eald", "old"],
["eard (m.)", "estate"],
["eardian", "dwell"],
["earm", "poor"],
["ebbian", "ebb away"],
["ecg (f.)", "edge"],
["endian", "finish, end"],
["endleofon", "eleven"],
["Englaland", "England"],
["Engle", "Angles, Englishmen"],
["erian", "plough"],
["ero&eth;lic", "worldly"],
["ero&eth;ling (m.)", "a farmer, ploughman"],
["e&#x0304;ac", "also"],
["fandian", "try, test"],
["faran", "travel"],
["fa&#x0304;h", "hostile"],
["fealu", "dark"],
["ferian", "carry"],
["fe&#x0304;dan", "feed"],
["fe&#x0304;ower", "four"],
["fe&#x0304;owertig", "forty"],
["fe&#x0304;owerti&#x0304;ene", "fourteen"],
["fi&#x0304;f", "five"],
["fi&#x0304;ftig", "fifty"],
["fla&#x0304;h", "treacherous"],
["fli&#x0304;eman", "drive off, rout"],
["flo&#x0304;wan", "flow"],
["folc (n.)", "a folk, nation"],
["folgian", "follow"],
["for", "for, on behalf of"],
["fore", "before, in front of"],
["forhtian", "be afraid, fear"],
["for&eth;&aelig;&#x0304;m &eth;e", "because of"],
["fo&#x0304;t (m.)", "foot"],
["fram", "from"],
["fremman", "carry out, perform"],
["fre&#x0304;oh", "free"],
["fre&#x0304;ond (m.)", "friend"],
["gaderian", "gather"],
["galdor (n.)", "charm"],
["ga&#x0304;n", "go"],
["gearu", "ready, prepared"],
["gefeoht (n.)", "battle, fight"],
["geha&#x0304;lsian", "take an oath"],
["geond", "across, throughout"],
["gesi&#x0304;&eth; (m.)", "a companion, fellow traveller"],
["ge&aelig;&#x0304;metigan", "empty"],
["giefan", "give"],
["giefu (f.)", "gift"],
["gi&#x0304;eman", "heed, obey"],
["glo&#x0304;f (f.)", "glove"],
["gl&aelig;d", "happy"],
["go&#x0304;d", "good"],
["go&#x0304;s (f.)", "goose"],
["gram", "fierce, angry"],
["habban", "have"],
["heard", "hard"],
["helpan", "help"],
["here (m.)", "raiding party, enemy army"],
["hergian", "ravage, to harry"],
["herian", "praise"],
["he&#x0304;ah", "high"],
["he&#x0304;awan", "hew"],
["hierde (m.)", "herdsman"],
["hi&#x0304;eran", "hear"],
["hi&#x0304;ersumian", "obey"],
["hla&#x0304;f (m.)", "loaf"],
["hors (n.)", "horse"],
["hre&#x0304;owan", "rue"],
["hund, hundred, hundtigontig", "100"],
["hundeahtatig", "80"],
["hundendleofontig", "110"],
["hundseofontig", "70"],
["hundtwelftig", "120"],
["hu&#x0304;s (n.)", "house"],
["hwy&#x0304;", "why?"],
["hw&aelig;t", "bold, daring"],
["hyll (f.)", "hill"],
["h&aelig;&#x0304;lan", "heal, make whole"],
["land (n.)", "land"],
["la&#x0304;f (f.)", "inheritance"],
["la&#x0304;r (f.)", "learning, knowledge"],
["la&#x0304;&eth;lic", "hateful"],
["leornian", "learn"],
["lettan", "hinder"],
["le&#x0304;ode", "people"],
["le&#x0304;of", "dear, precious"],
["li&eth;mann (m.)", "sailor"],
["lof (n.)", "praise"],
["longsum", "enduring"],
["losian", "be lost"],
["lo&#x0304;cian", "look"],
["lufian", "love"],
["lufsum", "lovable"],
["lu&#x0304;s (f.)", "louse"],
["ly&#x0304;tel", "small"],
["l&aelig;&#x0304;ce (m.)", "a healer, doctor"],
["l&aelig;&#x0304;fan", "leave behind"],
["l&aelig;&#x0304;ran", "teach"],
["macian", "make"],
["mann (m.)", "man"],
["ma&eth;elian", "make a speech"],
["mid", "with"],
["mo&#x0304;na (m.)", "moon"],
["munt (m.)", "mount, hill"],
["mu&#x0304;s (f.)", "mouse"],
["mynster (n.)", "minister-church"],
["m&aelig;&#x0304;re", "famous, renowned"],
["na&#x0304;", "not at all"],
["na&#x0304;n", "none"],
["ne... ne", "neither ... nor"],
["nearu", "narrow, close"],
["nerian", "save"],
["ne&#x0304;ah", "near"],
["nigon", "nine"],
["niht (f.)", "night"],
["ni&#x0304;edan", "compel, to force"],
["Nor&eth;anhymbre", "Northumbrians"],
["n&aelig;lles", "by no means"],
["n&aelig;&#x0304;fre", "never"],
["of", "off, from, away from"],
["ofer", "over, beyond, the other side of"],
["oftost", "most often"],
["on", "onto, into, against"],
["oneardian", "live in, to inhabit"],
["onge&#x0304;an", "towards, against"],
["o&eth;", "as far as, until, up to"],
["o&eth;&eth;e", "or"],
["ra&#x0304;p (m.)", "rope"],
["ri&#x0304;ce (n.)", "kingdom"],
["ri&#x0304;ce", "powerful"],
["ri&#x0304;dan", "ride"],
["ru&#x0304;m", "spacious, roomy"],
["ry&#x0304;man", "make room"],
["r&aelig;&#x0304;ran", "raise, rear"],
["sacu (f.)", "strife"],
["sa&#x0304;r", "sore"],
["sa&#x0304;rian", "be painful"],
["sce&#x0304;ap (n.)", "sheep"],
["scip (n.)", "ship"],
["sci&#x0304;nan", "shine"],
["scwe&#x0304;awian", "look at, inspect"],
["Seaxe", "Saxons"],
["seldan", "seldom"],
["seofon", "seven"],
["settan", "set"],
["se&#x0304;can", "seek"],
["se&#x0304;oc", "sick"],
["siex", "six"],
["siextig", "sixty"],
["sm&aelig;l", "slender"],
["sorgian", "sorrow, grieve"],
["so&#x0304;na", "soon"],
["spyrian", "ask, inquire"],
["standan", "stand"],
["sta&#x0304;n (m.)", "stone"],
["stede (m.)", "place"],
["ste&#x0304;orbord (n.)", "starboard"],
["sunne (f.)", "sun"],
["sweorcan", "darken"],
["sweord (n.)", "sword"],
["swe&#x0304;te", "sweet"],
["swi&#x0304;&eth;e", "very much, greatly"],
["talu (f.)", "tale"],
["til", "good, gainful"],
["ti&#x0304;en", "ten"],
["to&#x0304;&eth; (m.)", "tooth"],
["tre&#x0304;ow (n.)", "tree"],
["trum", "firm, stout"],
["tru&#x0304;wian", "trust, to believe"],
["trymman", "strengthen"],
["tungol  (n.)", "star"],
["tu&#x0304; hund", "200"],
["tu&#x0304; &eth;u&#x0304;sund", "2000"],
["twelf", "twelve"],
["twentig", "twenty"],
["twe&#x0304;gen", "two"],
["twe&#x0304;olic", "doubtful"],
["&eth;egn (m.)", "thane"],
["&eth;re&#x0304;oti&#x0304;ene", "thirteen"],
["&eth;ri&#x0304;e", "three"],
["&eth;ri&#x0304;tig", "thirty"],
["&eth;urh", "through, by means of"],
["&eth;u&#x0304;sund", "1000"],
["&eth;weorh", "awkward, perverse"],
["wadan", "walk"],
["weaxan", "grow"],
["weor&eth;ian", "honour"],
["wer (m.)", "man"],
["werian", "protect"],
["we&#x0304;nan", "expect, hope, suppose"],
["wif (f.)", "woman"],
["wilsum", "enjoyable"],
["wi&eth;", "against, towards, along"],
["wi&#x0304;cing (m.)", "viking"],
["word (n.)", "word"],
["wull (f.)", "wool"],
["wundian", "wound"],
["wunian", "remain, to dwell"],
["yfel", "evil"],
["ylde", "men, human beings"],
["ylfe", "elves"],
["ymb", "around, about"]
];
